apiVersion: v1
kind: Service
metadata:
  name: yolov8-ocr-service
  labels:
    app: yolov8-ocr
spec:
  type: LoadBalancer
  selector:
    app: yolov8-ocr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001