name: MLOpsPipeline

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install tesseract
        run: sudo apt-get install -y tesseract-ocr

      - name: Set env for Tesseract
        run: echo "TESSERACT_CMD=/usr/bin/tesseract" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Configure Kaggle API credentials
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\", \"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Run tests with coverage
        run: |
          PYTHONPATH=src pytest tests/ --cov=src

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push multi-arch image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ludovicmarion/orchestration_lm_bf:latest --push .