name: MLOpsPipeline

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install tesseract
        run: sudo apt-get install -y tesseract-ocr

      - name: Set env for Tesseract
        run: echo "TESSERACT_CMD=/usr/bin/tesseract" >> $GITHUB_ENV
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Configure Kaggle API credentials
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\", \"key\":\"${{ secrets.KAGGLE_KEY }}\"}" | tee ~/.kaggle/kaggle.json > ./kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Run tests with coverage
        run: |
          PYTHONPATH=src pytest tests/ --cov=src

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t ludovicmarion/orchestration_lm_bf:amd64 .
          docker build --platform linux/arm64 -t ludovicmarion/orchestration_lm_bf:arm64 .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ludovicmarion/orchestration_lm_bf:amd64
          docker push ludovicmarion/orchestration_lm_bf:arm64
          docker manifest create ludovicmarion/orchestration_lm_bf:latest \
            ludovicmarion/orchestration_lm_bf:amd64 \
            ludovicmarion/orchestration_lm_bf:arm64
          docker manifest push ludovicmarion/orchestration_lm_bf:latest

      - name: Run EasyOCR once to cache models
        run: |
          docker run --rm ludovicmarion/orchestration_lm_bf:latest python -c "import easyocr; easyocr.Reader(['fr', 'en'], download_enabled=True)"